import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = { title: "Terms & Conditions — Fluenta" };

export default function TermsPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 px-4 py-16">
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-1.5 text-sm text-muted hover:text-foreground"
      >
        <ArrowLeft size={14} />
        Back home
      </Link>
      <h1 className="mb-2 text-3xl font-semibold text-foreground">Terms & Conditions</h1>
      <p className="mb-10 text-sm text-muted">Last updated: August 2026</p>

      <div className="flex flex-col gap-8 text-sm leading-relaxed text-muted [&_h2]:mb-2 [&_h2]:text-base [&_h2]:font-semibold [&_h2]:text-foreground">
        <section>
          <h2>1. Using Fluenta</h2>
          <p>
            Fluenta is an AI-powered interview practice and English-fluency coaching tool. By
            creating an account or using the site, you agree to these terms. You must be at
            least 13 years old to use Fluenta.
          </p>
        </section>

        <section>
          <h2>2. Your account</h2>
          <p>
            You&apos;re responsible for keeping your login credentials secure and for all
            activity under your account. Let us know right away if you suspect unauthorized
            access.
          </p>
        </section>

        <section>
          <h2>3. AI-generated content</h2>
          <p>
            Company research, interview questions, feedback, and lessons are generated by an
            AI model and may contain inaccuracies. Fluenta is a practice tool, not a guarantee
            of interview or job outcomes — always verify important facts about a real employer
            independently.
          </p>
        </section>

        <section>
          <h2>4. Acceptable use</h2>
          <p>
            Don&apos;t use Fluenta to submit unlawful, abusive, or harmful content, attempt to
            disrupt the service, or reverse-engineer the platform. We may suspend or terminate
            accounts that violate these terms.
          </p>
        </section>

        <section>
          <h2>5. Your content</h2>
          <p>
            Resumes, job descriptions, and other files you upload are used only to personalize
            your practice sessions. You retain ownership of anything you upload; you can delete
            your account and data at any time from Account settings.
          </p>
        </section>

        <section>
          <h2>6. Subscriptions</h2>
          <p>
            Some features may require a paid subscription. Pricing and billing terms, when
            applicable, will be shown clearly before you pay.
          </p>
        </section>

        <section>
          <h2>7. Disclaimer & liability</h2>
          <p>
            Fluenta is provided &ldquo;as is&rdquo; without warranties of any kind. To the
            fullest extent permitted by law, Fluenta is not liable for any indirect or
            consequential damages arising from your use of the service.
          </p>
        </section>

        <section>
          <h2>8. Changes to these terms</h2>
          <p>
            We may update these terms from time to time. Continued use of Fluenta after changes
            means you accept the updated terms.
          </p>
        </section>

        <section>
          <h2>9. Contact</h2>
          <p>
            Questions about these terms? Reach out via the{" "}
            <Link href="/contact" className="text-accent hover:text-accent-hover">
              contact page
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
